# Generated by Django 2.0 on 2018-01-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('censo', '0013_auto_20180102_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deuda', models.FloatField(null=True)),
                ('anio', models.IntegerField(null=True)),
                ('fecha_carga', models.DateField(null=True)),
                ('pagado', models.BooleanField()),
                ('casa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Casa')),
                ('mes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Mes')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=30, null=True)),
                ('fecha', models.DateField(null=True)),
                ('observacion', models.TextField(null=True)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(null=True)),
                ('concepto', models.TextField(null=True)),
                ('deuda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finanzas.Deuda')),
                ('oficio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Oficio')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(null=True)),
                ('pago', models.FloatField(null=True)),
                ('concepto', models.CharField(max_length=30, null=True)),
                ('casa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Casa')),
                ('deuda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finanzas.Deuda')),
            ],
        ),
    ]
