# Generated by Django 2.0 on 2017-12-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0003_auto_20171228_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='candidatura',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Candidatura'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='eleccion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Eleccion'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='titulo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='calle',
            name='nombre',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='calle',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='casa',
            name='calle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Calle'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='cantidad_habitaciones',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='foto',
            field=models.ImageField(blank=True, upload_to='casas/'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='casa',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cronogramaguardia',
            name='hora_fin',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cronogramaguardia',
            name='hora_inicio',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cronogramaguardia',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cronogramaguardia',
            name='titulo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='anio',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='casa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Casa'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='deuda',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='fecha_carga',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='mes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Mes'),
        ),
        migrations.AlterField(
            model_name='discapacidad',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='titulo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='etnia',
            name='etnia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='familia',
            name='casa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Casa'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='concepto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='persona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Persona'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='grado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='grado',
            name='institucion_educativa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.InstitucionEducativa'),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='persona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Persona'),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='habilidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='institucion_educativa',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mes',
            name='mes',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='concepto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='deuda',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Deuda'),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='fecha_entrega',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='oficio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Oficio'),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='persona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Persona'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='oficio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='casa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Casa'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='deuda',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Deuda'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pago',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='pariente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pariente', to='censo.Persona'),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='persona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='persona', to='censo.Persona'),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='tipoParentesco',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.TipoParentesco'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='etnia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Etnia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='familia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Familia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, upload_to='casas/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='habilidad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Habilidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ingreso_mensual',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='oficio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Oficio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ultimo_grado_aprobado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Grado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='vive_desde',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tipoparentesco',
            name='tipoParentesco',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='institucion_educativa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.InstitucionEducativa'),
        ),
        migrations.AlterField(
            model_name='tratamientopermanente',
            name='enfermedad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tratamientopermanente',
            name='medicina',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='candidato',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Candidatura'),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='hora',
            field=models.TimeField(blank=True),
        ),
    ]
