# Generated by Django 2.1.7 on 2019-02-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='static/casas/')),
                ('numero', models.CharField(max_length=10, null=True)),
                ('observaciones', models.TextField(null=True)),
                ('cantidad_habitaciones', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, null=True)),
                ('documento', models.ImageField(null=True, upload_to='static/documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_educativa', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='static/personas/')),
                ('cedula', models.CharField(max_length=10, null=True)),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('apellido', models.CharField(max_length=20, null=True)),
                ('discapaz', models.BooleanField()),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('vive_desde', models.IntegerField(null=True)),
                ('indigena', models.BooleanField()),
                ('ingreso_mensual', models.FloatField(null=True)),
                ('observaciones', models.TextField(null=True)),
                ('discapacidad', models.ManyToManyField(to='censo.Discapacidad')),
                ('documento', models.ManyToManyField(to='censo.Documento')),
                ('habilidad', models.ManyToManyField(to='censo.Habilidad')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Nacionalidad')),
                ('oficio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Oficio')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParentesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoParentesco', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('institucion_educativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.InstitucionEducativa')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Sexo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='titulos',
            field=models.ManyToManyField(to='censo.Titulo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ultimo_grado_aprobado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Grado'),
        ),
        migrations.AddField(
            model_name='parentesco',
            name='pariente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pariente', to='censo.Persona'),
        ),
        migrations.AddField(
            model_name='parentesco',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='persona', to='censo.Persona'),
        ),
        migrations.AddField(
            model_name='parentesco',
            name='tipoParentesco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.TipoParentesco'),
        ),
        migrations.AddField(
            model_name='grado',
            name='institucion_educativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.InstitucionEducativa'),
        ),
    ]
