# Generated by Django 2.1.7 on 2019-02-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='static/apartamentos/')),
                ('numero', models.CharField(max_length=10, null=True)),
                ('observaciones', models.TextField(null=True)),
                ('cantidad_habitaciones', models.IntegerField(null=True)),
            ],
        ),
    ]
