# Generated by Django 2.1.7 on 2019-02-27 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_auto_20190227_1457'),
        ('censo', '0002_apartamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Casa',
        ),
        migrations.AddField(
            model_name='persona',
            name='apartamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Apartamento'),
        ),
    ]
