# Generated by Django 2.0 on 2017-12-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0004_auto_20171228_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calle',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
