# Generated by Django 2.0 on 2018-01-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0006_auto_20180101_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.CharField(blank=True, max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='mision',
            field=models.ManyToManyField(to='censo.Mision'),
        ),
    ]
