# Generated by Django 2.0 on 2018-01-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0008_auto_20180102_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='habilidad',
        ),
        migrations.AddField(
            model_name='persona',
            name='habilidad',
            field=models.ManyToManyField(to='censo.Habilidad'),
        ),
    ]
