# Generated by Django 2.0 on 2018-01-02 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0009_auto_20180102_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientopermanente',
            name='informe_medico',
            field=models.ImageField(null=True, upload_to='informes_medicos/'),
        ),
        migrations.AddField(
            model_name='tratamientopermanente',
            name='recipe',
            field=models.ImageField(null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='candidatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Candidatura'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='eleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Eleccion'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='titulo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='calle',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calle',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='calle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Calle'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='cantidad_habitaciones',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='foto',
            field=models.ImageField(null=True, upload_to='casas/'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cronogramaguardia',
            name='hora_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cronogramaguardia',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cronogramaguardia',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cronogramaguardia',
            name='titulo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='anio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='casa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Casa'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='deuda',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='fecha_carga',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Mes'),
        ),
        migrations.AlterField(
            model_name='discapacidad',
            name='discapacidad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.ImageField(null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='titulo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='etnia',
            name='etnia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='casa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Casa'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='concepto',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='observacion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Persona'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='grado',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='grado',
            name='institucion_educativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.InstitucionEducativa'),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Persona'),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='habilidad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='institucion_educativa',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='mes',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='mision',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='concepto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='deuda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Deuda'),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='oficio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Oficio'),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Persona'),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='nacionalidad',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='oficio',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='casa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Casa'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='deuda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Deuda'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pago',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='pariente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pariente', to='censo.Persona'),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='persona', to='censo.Persona'),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='tipoParentesco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.TipoParentesco'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='etnia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Etnia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Familia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(null=True, upload_to='personas/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ingreso_mensual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='oficio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Oficio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Sexo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ultimo_grado_aprobado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Grado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='vive_desde',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='sexo',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tipoparentesco',
            name='tipoParentesco',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='institucion_educativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.InstitucionEducativa'),
        ),
        migrations.AlterField(
            model_name='tratamientopermanente',
            name='enfermedad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tratamientopermanente',
            name='medicina',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Candidatura'),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
