# Generated by Django 2.0 on 2018-01-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0010_auto_20180102_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/casas/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.ImageField(null=True, upload_to='static/documentos/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/personas/'),
        ),
        migrations.AlterField(
            model_name='tratamientopermanente',
            name='informe_medico',
            field=models.ImageField(null=True, upload_to='static/informes_medicos/'),
        ),
        migrations.AlterField(
            model_name='tratamientopermanente',
            name='recipe',
            field=models.ImageField(null=True, upload_to='static/recipes/'),
        ),
    ]
