# Generated by Django 2.0 on 2018-01-02 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0011_auto_20180102_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnetPatria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, null=True)),
                ('serial', models.CharField(max_length=15, null=True)),
                ('codigo', models.CharField(max_length=15, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='static/carnet_patria/')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='carnet_patria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.CarnetPatria'),
        ),
    ]
