# Generated by Django 2.0 on 2018-01-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0012_auto_20180102_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='candidatura',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='eleccion',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='persona',
        ),
        migrations.DeleteModel(
            name='CronogramaGuardia',
        ),
        migrations.RemoveField(
            model_name='deuda',
            name='casa',
        ),
        migrations.RemoveField(
            model_name='deuda',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='guardia',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='monedas',
            name='deuda',
        ),
        migrations.RemoveField(
            model_name='monedas',
            name='oficio',
        ),
        migrations.RemoveField(
            model_name='monedas',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='casa',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='deuda',
        ),
        migrations.RemoveField(
            model_name='votacion',
            name='candidato',
        ),
        migrations.DeleteModel(
            name='Boleta',
        ),
        migrations.DeleteModel(
            name='Candidatura',
        ),
        migrations.DeleteModel(
            name='Deuda',
        ),
        migrations.DeleteModel(
            name='Eleccion',
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
        migrations.DeleteModel(
            name='Guardia',
        ),
        migrations.DeleteModel(
            name='Monedas',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Votacion',
        ),
    ]
