# Generated by Django 2.0 on 2018-01-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('censo', '0013_auto_20180102_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaGuardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_fin', models.TimeField(null=True)),
                ('titulo', models.CharField(max_length=40, null=True)),
                ('observaciones', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(null=True)),
                ('fecha', models.DateField(null=True)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='censo.Persona')),
            ],
        ),
    ]
