# Generated by Django 2.0 on 2018-01-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='guardias.CronogramaGuardia'),
        ),
    ]
