# Generated by Django 2.0 on 2018-01-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('censo', '0013_auto_20180102_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('persona', models.ManyToManyField(to='censo.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(null=True)),
                ('candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='votacion.Candidatura')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='candidatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='votacion.Candidatura'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='eleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='votacion.Eleccion'),
        ),
    ]
